### ISSUE TITLE
Two inhomogeneous directions?

### ISSUE THREAD

**Issue by loiseaujc** [spectralDNS/shenfun#16]
Hej Mikael,

I have successfully written as small python code for two-dimensional turbulence using shenfun. I am planning to move on to a fully three-dimensional channel flow, and maybe eventually a duct flow. In that matter, it is written in the abstract of the shenfun paper:

> With the shenfun Python module (github.com/spectralDNS/shenfun) an effort is made towards automating the implementation of the spectral Galerkin method for simple tensor product domains, consisting of **(currently) one non-periodic** and any number of periodic directions.

Do you have any plan of adding eventually multiple (say just two to begin with) inhomogeneous directions? That would be extremely valuable for people interested in confined flows (e.g. lid-driven cavity flows or duct flow to mention just two of them).

Thanks a lot anyway for developing shenfun. A really cool package!

**Comment by mikaem** [comment]
Hej Sean-Christophe
Thanks a lot for your feedback:-) Have you seen this 2D [demo](https://github.com/spectralDNS/shenfun/blob/master/demo/dirichlet_dirichlet_poisson2D.py) with 2 inhomogeneous directions? The problem with 2 inhomogeneous directions is to create good linear algebra solvers. I have created one for two Dirichlet Legendre bases, but that's about it. Everything else should work out of the box, like transforms and projections, but the solvers are quite a bit more complicated than in 1D. See Shen's [papers](http://shenfun.readthedocs.io/en/latest/zrefs.html) and the sections about 2D. The solver [implemented ](https://github.com/spectralDNS/shenfun/blob/7c67ecdab2edc39eb8c23e0ac88bfc002502ed1a/shenfun/legendre/la.py#L425) for the demo corresponds to sec 2.2 in the first Shen reference. So there's no technical issue or problem really, it's just to find the time to actually do it:-)

**Comment by mikaem** [comment]
Hi,

Just wanted to make a note that with PR #21 there is now a generic solver for 2 inhomogeneous directions (see [link](https://github.com/spectralDNS/shenfun/blob/f2929ca8f8a701151a1b57ecb7ace3c9713c4074/shenfun/la.py#L355)). The solver makes use of sparse linear algebra from scipy, but is not highly optimized for speed. The solver is direct but the factorizations are (for now) not stored as would be efficient for multiple solves. Can be easily added later.

Some demos are::

- [biharmonic2D_2nonperiodic.py](https://github.com/spectralDNS/shenfun/blob/master/demo/biharmonic2D_2nonperiodic.py)
- [biharmonic3D_2nonperiodic.py](https://github.com/spectralDNS/shenfun/blob/master/demo/biharmonic3D_2nonperiodic.py)

**Comment by mikaem** [comment]
Great:-) I have also (slowly) been adding some[ more documentation](https://shenfun.readthedocs.io/en/latest/gettingstarted.html#multidimensional-problems), which may be of help in understanding how things actually work:-) 
I also have a new [Rayleigh-Bénard video](https://github.com/spectralDNS/spectralutilities/blob/master/movies/RayleighBenard.png). It's actually a 3D simulation using an optimized [spectralDNS](https://github.com/spectralDNS/spectralDNS/blob/master/spectralDNS/solvers/KMMRK3_RB.py) solver (which is using shenfun), and I'm waiting to get more CPU-hours such that I can run it with higher resolution. This one is 128x256x256.

**Comment by stefmech** [comment]
Hey Mikael,

thank you for providing such a cool package! For me it would be quite interesting to have a solver for 3 non-periodic directions (Legendre, Chebyshev). Are there any plans to extend this functionality?

**Comment by mikaem** [comment]
Hi @stefmech 

Three non-periodic directions are actually already possible. There may be limited possibilities in terms of linear algebra, but I just verified that this works:

    from shenfun import *
    import matplotlib.pyplot as plt
    D = FunctionSpace(16, 'L', bc=(0, 0))
    T = TensorProductSpace(comm, (D, D, D))
    u = TrialFunction(T)
    v = TestFunction(T)
    B = inner(u, v)
    Bd = B.diags()
    plt.spy(Bd, markersize=0.5)
