### ISSUE TITLE
Problem with Chebyshev basis?

### ISSUE THREAD

**Issue by loiseaujc** [spectralDNS/shenfun#19]
Hi Mikael,

I have started to implement my Rayleigh-Benard solver and wanted to play a bit with the Poisson and Biharmonic solvers first. To do so, I downloaded the scripts available in the `demo` folder and I have some weird things going on:

- For both the Poisson and Biharmonic scipts (2D ones), if I set the basis used in the non-homogeneous direction to be Chebyshev, the right-hand-side vector `f_hat = inner(v, fj, output_array=f_hat)` all its entries turn out be to equal to `0 + 0j`.
- If instead I set the basis to be Legendre polynomials, then everything works out correctly.

For information, I have installed shenfun using conda.

**Comment by mikaem** [comment]
Hi
That's really weird. The demos are run as part of the test-suit and there are no errors on Travis, Circle-Ci or my own mac. All using conda. Are you running the demo as, e.g.:: 

    python dirichlet_poisson2D 32 chebyshev?

Anything special about your installation? Are you building locally or downloading from the Anaconda channel?

**Comment by loiseaujc** [comment]
Weird indeed.

I do run the script using the command you mentioned. Regarding shenfun, I installed using:

`conda install -c conda-forge -c spectralDNS python=3.6 shenfun`

**Comment by mikaem** [comment]
Did you install in a new conda environment? I assume you have cloned or forked the repository since you have the demos? If you uninstall the conda version (conda uninstall shenfun (this leaves the dependencies installed)) and add

    export PYTHONPATH=~/where_shenfun_is_located/:$PYTHONPATH

Then do

    python setup.py build_ext --inplace

Now change to demo folder and run the demo again. Also, I realised yesterday the mkl had broken some tests on circle-ci, which is why I now in the latest version of shenfun have ``nomkl`` as a dependency. But that may not have migrated to the binaries yet.

**Comment by loiseaujc** [comment]
I am not 100% sure if its related, but here is the error I get if I run the same script with python 2.7;

```
/home/jean-christophe/anaconda3/envs/shenfun_test/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "poisson_2D.py", line 51, in <module>
    T = TensorProductSpace(comm, (SD, K1), axes=(0, 1))
  File "/home/jean-christophe/anaconda3/envs/shenfun_test/lib/python2.7/site-packages/shenfun/tensorproductspace.py", line 118, in __init__
    xfftn.plan(pencilB.subshape, axes, dtype, kw)
  File "/home/jean-christophe/anaconda3/envs/shenfun_test/lib/python2.7/site-packages/shenfun/chebyshev/bases.py", line 385, in plan
    self.CT.plan(shape, axis, dtype, options)
  File "/home/jean-christophe/anaconda3/envs/shenfun_test/lib/python2.7/site-packages/shenfun/chebyshev/bases.py", line 140, in plan
    xfftn_fwd = plan_fwd(U, axis=axis, **opts)
  File "build/bdist.linux-x86_64/egg/pyfftw/builders/builders.py", line 549, in dct
  File "build/bdist.linux-x86_64/egg/pyfftw/builders/_utils.py", line 205, in _Xfftn
  File "pyfftw/pyfftw.pyx", line 1252, in pyfftw.pyfftw.FFTW.__cinit__ (/home/mikael/anaconda2/conda-bld/work/pyfftw/pyfftw.c:11613)
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.

```
Once again, if I set the basis to Legendre, the python 2.7 version works perfectly.

**Comment by loiseaujc** [comment]
Nope, I did not fork. I simply downloaded the demo folder directly from GitHub.

**Comment by mikaem** [comment]
Exactly, I saw that error message yesterday for the mpi4py-fft code. It is caused by numpy using mkl. I will rebuild shenfun with nomkl and upload a new binary.

**Comment by mikaem** [comment]
Should be ready now. Build version 7.

**Comment by loiseaujc** [comment]
Awesome! It now works like a charm. Thanks a lot.

I will get back to you whenever I am done with my 2D Rayleigh-Benard solver. Once it works (and has been validated), I can eventually send a pull request to add it to the demos if you want.
