### ISSUE TITLE
pyFFTW runtimeerror with dirichlet_Poisson2D demo

### ISSUE THREAD

**Issue by MiroK** [spectralDNS/shenfun#2]
With shenfun built and installed by conda running `dirichlet_Poisson2D.py` from `demo` folder produced

> /home/miro3/miniconda2/envs/SHENFUN/lib/python2.7/site-packages/matplotlib/font_manager.py:280: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
>   'Matplotlib is building the font cache using fc-list. '
> 
> Traceback (most recent call last):
>   File "dirichlet_poisson2D.py", line 52, in <module>
>     T = TensorProductSpace(comm, (SD, K1))
>   File "/home/miro3/miniconda2/envs/SHENFUN/lib/python2.7/site-packages/shenfun/tensorproductspace.py", line 79, in __init__
>     xfftn.plan(pencilB.subshape, axes, dtype, kw)
>   File "/home/miro3/miniconda2/envs/SHENFUN/lib/python2.7/site-packages/shenfun/chebyshev/bases.py", line 405, in plan
>     self.CT.plan(shape, axis, dtype, options)
>   File "/home/miro3/miniconda2/envs/SHENFUN/lib/python2.7/site-packages/shenfun/chebyshev/bases.py", line 147, in plan
>     xfftn_fwd = plan_fwd(U, axis=axis, **opts)
>   File "build/bdist.linux-x86_64/egg/pyfftw/builders/builders.py", line 549, in dct
>   File "build/bdist.linux-x86_64/egg/pyfftw/builders/_utils.py", line 205, in _Xfftn
>   File "pyfftw/pyfftw.pyx", line 1252, in pyfftw.pyfftw.FFTW.__cinit__ (/home/mikael/anaconda2/conda-bld/work/pyfftw/pyfftw.c:11613)
> RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.

**Comment by mikaem** [comment]
Thank you Miro. This is a pyFFTW bug. It can be fixed by importing `pyfftw` before numpy. For example by setting `import pyfftw` in one of the first lines of the demo.
