### ISSUE TITLE
test_io.py error; mpi version problem?

### ISSUE THREAD

**Issue by fnauman** [spectralDNS/shenfun#23]
Hi,

When I run:
bash rundemos.sh

all the demos run successfully. However, when I run:
python -m pytest .

(from shenfun/tests/ folder)

I run into the MPI error (attached below). 

I used:
conda create --name shenfun_prec -c conda-forge -c spectralDNS shenfun

to create this shenfun environment in conda.

I also tried building the environment using instructions here:
https://shenfun.readthedocs.io/en/latest/installation.html

and I run into the same exact error. 

Moreoever, running (after installing spectralDNS):
mpirun -np 4 python TG.py NS

for spectralDNS ends up with the same error as well (spectralDNS library, not shenfun). 

Is it a way to fix this? 

Thanks,
Farrukh

============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /home/fnauman/python3/shenfun, inifile:
collected 3539 items / 1 errors                                                

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_io.py _______________________
test_io.py:13: in <module>
    import h5py
../../../anaconda3/envs/shenfun_prec/lib/python3.6/site-packages/h5py/__init__.py:24: in <module>
    from . import _errors
MPI.pxd:28: in init h5py._errors
    ???
E   **ValueError: mpi4py.MPI.Status has the wrong size, try recompiling. Expected 48, got 40**
=============================== warnings summary ===============================
/home/fnauman/anaconda3/envs/shenfun_prec/lib/python3.6/site-packages/shenfun/forms/arguments.py:510
  /home/fnauman/anaconda3/envs/shenfun_prec/lib/python3.6/site-packages/shenfun/forms/arguments.py:510: PytestWarning: cannot collect test class 'TestFunction' because it has a __init__ constructor
    class TestFunction(BasisFunction):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 1 warnings, 1 error in 1.74 seconds ======================

**Comment by mikaem** [comment]
This is likely an MPI version error. I tried googling for the error message: `ValueError: mpi4py.MPI.Status has the wrong size, try recompiling. Expected 48, got 40` and got this [link](https://groups.google.com/forum/#!topic/mpi4py/Homqi5iJmT4) as the first hit. Probably h5py was built with different mpi version than mpi4py.

Note that right now I'm trying to rebuild spectralDNS with parallel hdf5/h5py from conda-forge, which was  recently [made available](https://github.com/conda-forge/hdf5-feedstock/issues/51). When that is in place everything should (hopefully) run smoothly.

**Comment by fnauman** [comment]
**Update:**

h5py parallel issue seems to be resolved now.

I tried different versions of h5py, mpi4py on conda but that was not helping but following the mpi4py thread linked in mikaem's response, I did:
`
import mpi4py
mpi4py.MPI.get_vendor()
('Open MPI', (2, 1, 1))
mpi4py.__file__
'/home/fnauman/.local/lib/python3.6/site-packages/mpi4py/__init__.py'
`

which made me realize that the code was using a global 'pip' installed mpi4py instead of the conda environment's mpi4py. I removed this using *pip3 uninstall mpi4py*. Ran the tests again, and at least the h5py configuration seems to work!!

However, there are 7 other errors, seem to be all related to netCDF. 
https://gist.github.com/fnauman/8e51f41316710a8621e5d5cdb864c9ea

**Comment by mikaem** [comment]
Yes, I get those too. There's an issue with the latest version of NetCDF and my suggestion would be to simply ignore it if you don't rely on NetCDF. I'm disabling these tests at the moment. You don't need or import the NetCDF module unless you are using it. There's no problem anymore with HDF5, though, and you should now be able to use HDF5/h5py from conda-forge.

**Comment by fnauman** [comment]
Thanks. I checked out the most recent version of shenfun and indeed most tests pass except one, related to *subprocess.py* in demos:
> __________________________________ test_demos __________________________________
>
>     def test_demos():
>         subprocess.check_output("/bin/bash rundemos.sh", shell=True,
> >                               cwd=os.path.join(os.getcwd(), "tests"))
> 
> test_demos.py:7: 
> 
> ../../../anaconda3/envs/shenfun/lib/python3.6/subprocess.py:336: in check_output
>     **kwargs).stdout
> ../../../anaconda3/envs/shenfun/lib/python3.6/subprocess.py:403: in run
>     with Popen(*popenargs, **kwargs) as process:
> ../../../anaconda3/envs/shenfun/lib/python3.6/subprocess.py:709: in __init__
>     restore_signals, start_new_session)
> ....
> E               FileNotFoundError: [Errno 2] No such file or directory: '/home/fnauman/python3/shenfun/tests/tests': '/home/fnauman/python3/shenfun/tests/tests'
> 
> ../../../anaconda3/envs/shenfun/lib/python3.6/subprocess.py:1344: FileNotFoundError

I can confirm the tests in spectralDNS work as well. 

Thanks for your help!!

**Comment by fnauman** [comment]
Thanks, I tried running it from the (git repo) root folder and now I get 8 errors. I guess it is because it is treating the shenfun folder as the source of shenfun module because the errors are module load errors such as:

> No module named 'shenfun.optimization.cython.la'

I tried running it from a different folder and the error reported earlier persists. I am not sure what could be going wrong.

> =================================== FAILURES ==================================
> __________________________________ test_demos __________________________________
> 
>     def test_demos():
>         subprocess.check_output("/bin/bash rundemos.sh", shell=True,
> 

>                               cwd=os.path.join(os.getcwd(), "tests"))

> ../shenfun/tests/test_demos.py:7: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../anaconda3/envs/shenfun_prec/lib/python3.6/subprocess.py:336: in check_output
>     **kwargs).stdout
> ...
> E               subprocess.CalledProcessError: Command '/bin/bash rundemos.sh' returned non-zero exit status 127.
> 
> ../../anaconda3/envs/shenfun_prec/lib/python3.6/subprocess.py:418: CalledProcessError
> ----------------------------- Captured stderr call -----------------------------
> /bin/bash: rundemos.sh: No such file or directory
