### ISSUE TITLE
mhd problem: floating precision issue?

### ISSUE THREAD

**Issue by fnauman** [spectralDNS/shenfun#27]
I was trying to use MHD.py in (spectralDNS/solvers) with shenfun since that example uses shenfun to setup the problem anyway. I ran the Taylor Green problem and at the end there is an assertion error. The answer is turning out to be 0.125 while it should be:
```python
        assert np.round(k - 0.124565408177, 7) == 0
        assert np.round(b - 0.124637762143, 7) == 0
```

The full file can be seen here:
https://gist.github.com/fnauman/e105bdf901616345b70145c6ded7c963#file-tgmhd_shenfun-py

On a related note: At the beginning of the NavierStokes.py demo, you mention
> Not implemented for efficiency

How slow is the shenfun implementation compared to spectralDNS? (and why, if I may ask?)

**Comment by mikaem** [comment]
Working MHD solver [here](https://gist.github.com/mikaem/3966135fda6c15aba0999853d9045ac9)

The NavierStokes solver is slower than spectralDNS mainly because of the cross product. This is rather slow using Numpy and vectorization. If I remember correctly, the Cython or Numba versions are approximately 3 times faster. Other then that there's not really much of a difference.

**Comment by fnauman** [comment]
Thanks @mikaem for your quick response. I was making two mistakes: (i) placing pressure in the LinearRHS function, and (ii) I also realized in the shenfun's interface, u_hat or b_hat should not be multiplied inside of the linear function since they are multiplied in the integrator call. But the part that I am a little confused about is why you choose to use inner products instead of simply using `-K^2 * nu`:
```python
    L = inner(div(grad(u)), v).scale
    L = np.broadcast_to(L[np.newaxis, ...], (6,)+L.shape).copy()
    L[:3] *= nu
    L[3:] *= eta
```
Is this faster?

**Comment by mikaem** [comment]
They are equivalent and you should not get an assertion error. I don't. The latter version (with K2) is slightly faster to assemble (they are equivalent inside the integrator) than the first, but I think the first is more descriptive.

**Comment by fnauman** [comment]
Thanks!
