### ISSUE TITLE
warnings on test_io

### ISSUE THREAD

**Issue by francispoulin** [spectralDNS/shenfun#37]
This is not a bug but when I test test_io I get a warning, which I presume you would want to fix up sometime?

`(shenfun) fpoulin@amlt21:~$ python -m pytest software/shenfun/tests/test_io.py 
=============================== test session starts ===============================
platform linux -- Python 3.8.1, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/fpoulin/software/shenfun
collected 24 items                                                                

software/shenfun/tests/test_io.py ........................                  [100%]

================================ warnings summary =================================
software/anaconda3/envs/shenfun/lib/python3.8/site-packages/shenfun/forms/arguments.py:700
  /home/fpoulin/software/anaconda3/envs/shenfun/lib/python3.8/site-packages/shenfun/forms/arguments.py:700: PytestCollectionWarning: cannot collect test class 'TestFunction' because it has a __init__ constructor (from: tests/test_io.py)
    class TestFunction(BasisFunction):

tests/test_io.py::test_regular_2D[hdf5-False]
tests/test_io.py::test_mixed_2D[True-hdf5-False]
tests/test_io.py::test_mixed_2D[False-hdf5-False]
tests/test_io.py::test_regular_3D[hdf5-False]
tests/test_io.py::test_mixed_3D[True-hdf5-False]
tests/test_io.py::test_mixed_3D[False-hdf5-False]
  /home/fpoulin/software/anaconda3/envs/shenfun/lib/python3.8/site-packages/mpi4py_fft/io/generate_xdmf.py:117: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
    f = h5py.File(h5filename)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================= 24 passed, 7 warnings in 1.35s ==========================
`

**Comment by mikaem** [comment]
Yes, this should definitively be taken care of. But it's actually an mpi4py-fft issue, so I'll fix it over there:-)

**Comment by francispoulin** [comment]
Thanks for fixing it and next time maybe I'll figure out what in particular needs to be fixed.
