### ISSUE TITLE
matplotlib is missing in the conda package

### ISSUE THREAD

**Issue by sebglane** [spectralDNS/shenfun#46]
Hi,
it occurred to me that `matplotlib` is missing in the conda package. It can of course be easily installed later. However it would be convenient if it is added to the package.
Best wishes,
Sebastian

**Comment by mikaem** [comment]
Hi
Convenient, yes, but `matplotlib` is actually missing by choice to keep the number of dependencies to a minimum. It is not required, even though it is used by many demos. Some users will prefer other plotting tools and, in my opinion, should not be forced to install the huge `matplotlib` package if they don't want to.
