### ISSUE TITLE
Time dependent boundary conditions in segments for Rayleigh-Benard 2D

### ISSUE THREAD

**Issue by VikasChidananda** [spectralDNS/shenfun#98]
Hello, 

Is there a way to control the boundary conditions in several segments and varying in time, especially for the case of RayleighBenard2D? 
I would like to achieve something that's been done as in [here](https://arxiv.org/pdf/2003.14358.pdf).

![image](https://github.com/spectralDNS/shenfun/assets/64703416/9bcca784-d0a0-4037-bc9b-6150a84639b4)

In essence having ,

```Python
bcT[1] = (0.2, 0.3, 0.4, 0.5, 0.1)
``` 
where the lower Temperature is divided into 5 segments / or any arbitrary segments ?

**Comment by mikaem** [comment]
Hei
Yes, this has been done [here](https://arxiv.org/abs/2304.02370). You can use some sympy function that approximates a hat function, and then simply use it as [here](https://github.com/spectralDNS/shenfun/blob/274f4b89c7a0d9bc87215ea33bdcb72f3112e36f/demo/RayleighBenard2D.py#L200).

**Comment by VikasChidananda** [comment]
Thank you!
